#!/bin/env/python python3

def sum(list):
    counted_sum = 0
    for i in list:
        counted_sum += i
    return counted_sum
    

def multiply(list):
    counted_multiply = 1
    for i in list:
        counted_multiply *= i 
    return counted_multiply


print(sum([1, 2, 3, 4]))
print(multiply([1, 2, 3, 4]))
print(multiply([1, 2, 3, 4, 10 ]))
   



