#!/bin/env/python python3
import time

def histogram(list):
    print("Start visualization!")
    for i in list : 
        for j in range(i):
            time.sleep(0.5)
            print("*", end = ' ', flush=True)
        print("")
        time.sleep(0.5)
    print("End")

histogram([4, 9, 7])
histogram([4, 9, 7,0,1,9])
histogram([1,2,3,4,5,6,7,8,9,8,7,6,5,4,3,2,1])
